from pathlib import Path
import hashlib, base64

p=Path('net-cao-hon-co-that-tot-hon-v2.html')
s=p.read_text()

def rep(old,new,label):
    global s
    if old not in s: raise SystemExit(f'Missing target: {label}')
    s=s.replace(old,new,1)

# Clearer data actions, error wording, privacy and legal dates.
s=s.replace('↓ Tải về (.json)','↓ Tải dữ liệu (.json)',1)
s=s.replace('↑ Nhập</button>','↑ Nhập dữ liệu (.json)</button>',1)
s=s.replace('Chế độ tạm - dùng Tải về để giữ dữ liệu','Chế độ tạm - dùng Tải dữ liệu để giữ dữ liệu')
s=s.replace('Không lưu được - thử Tải về','Không lưu được - thử Tải dữ liệu')
s=s.replace('Ngày phép được dùng để điều chỉnh time cost, không cộng trực tiếp vào thu nhập năm.','Ngày phép được dùng để giảm thời gian bạn bỏ ra khi tính giá trị/giờ, không cộng trực tiếp vào thu nhập năm.')
s=s.replace('Dữ liệu được gửi tới máy chủ để tính toán nhưng website không chủ động lưu vào cơ sở dữ liệu; nếu bấm Lưu, dữ liệu được giữ trên trình duyệt của bạn.','Dữ liệu offer được gửi tới máy chủ để tính toán. Ứng dụng không ghi nội dung offer vào cơ sở dữ liệu; nếu bấm Lưu, dữ liệu được giữ trên trình duyệt của bạn.')

old_footer='<p class="src"><b>Tham số đang dùng:</b> Tool dùng các tham số hiện hành từ 01/07/2026. Tiền lương làm thêm giờ được miễn PIT trong kỳ tính thuế 2026. PIT 5 bậc: 5% - 10% - 20% - 30% - 35% theo các ngưỡng 10 - 30 - 60 - 100 triệu đồng/tháng; giảm trừ 15,5 triệu cho bản thân và 6,2 triệu/người phụ thuộc. NLĐ đóng BH chuẩn 10,5%; căn cứ BHXH/BHYT tối đa 50,6 triệu/tháng từ 01/07/2026; BHTN tối đa 20× lương tối thiểu vùng. LTT vùng 2026: I 5,31 triệu; II 4,73 triệu; III 4,14 triệu; IV 3,70 triệu. Trợ cấp thất nghiệp 60% bình quân 6 tháng đóng BHTN, tối đa 5× LTT vùng; thai sản theo bình quân 6 tháng đóng BHXH; ốm đau thông thường = căn cứ BHXH ÷ 24 × 75% × số ngày. Nguồn pháp lý chính: Bộ luật Lao động 45/2019/QH14; NĐ 145/2020/NĐ-CP; Luật Thuế TNCN 109/2025/QH15; Luật BHXH 41/2024/QH15; NĐ 158/2025/NĐ-CP; Luật Việc làm 74/2025/QH15; NĐ 293/2025/NĐ-CP.</p>'
new_footer='<p class="src"><b>Tham số đang dùng:</b> PIT 5 bậc 5% - 10% - 20% - 30% - 35% theo các ngưỡng 10 - 30 - 60 - 100 triệu đồng/tháng và miễn thuế toàn bộ tiền lương làm thêm giờ: áp dụng cho thu nhập tiền lương, tiền công của kỳ tính thuế 2026. Giảm trừ gia cảnh 15,5 triệu/tháng cho bản thân và 6,2 triệu/tháng/người phụ thuộc: hiệu lực từ 01/01/2026. Lương tối thiểu vùng từ 01/01/2026: I 5,31 triệu; II 4,73 triệu; III 4,14 triệu; IV 3,70 triệu. NLĐ đóng BH chuẩn 10,5%; căn cứ BHXH/BHYT tối đa 50,6 triệu/tháng từ 01/07/2026; BHTN tối đa 20× lương tối thiểu vùng. Trợ cấp thất nghiệp 60% bình quân 6 tháng đóng BHTN, tối đa 5× LTT vùng; thai sản theo bình quân 6 tháng đóng BHXH; ốm đau thông thường = căn cứ BHXH ÷ 24 × 75% × số ngày. Nguồn pháp lý chính: Bộ luật Lao động 45/2019/QH14; NĐ 145/2020/NĐ-CP; Luật Thuế TNCN 109/2025/QH15; Nghị quyết 110/2025/UBTVQH15; Luật BHXH 41/2024/QH15; NĐ 158/2025/NĐ-CP; Luật Việc làm 74/2025/QH15; NĐ 293/2025/NĐ-CP.</p>'
rep(old_footer,new_footer,'footer dates')

# Split the annual-package hint so the most common misunderstanding stands alone.
old_hint='<div class="layer"><p class="lnum">Lớp 2 · <b>Package năm</b></p><p class="hint" style="margin-top:-2px">So package năm theo 12 tháng chuẩn hóa: <b>Chắc chắn</b> không tính thưởng hiệu suất, và <b>Có thưởng hiệu suất</b> cộng đúng mức bạn đã nhập. Nếu không có khoản này, tool chỉ hiện phần chắc chắn. Đây không phải dòng tiền 12 tháng lịch kể từ ngày onboard. Tiền OT không nằm trong package năm này vì phụ thuộc số giờ OT thực tế; xem Lớp 3.</p><div class="cols" id="annualcols"></div>'
new_hint='<div class="layer"><p class="lnum">Lớp 2 · <b>Package năm</b></p><p class="hint" style="margin-top:-2px;margin-bottom:6px">So package năm theo 12 tháng chuẩn hóa: <b>Chắc chắn</b> không tính thưởng hiệu suất, và <b>Có thưởng hiệu suất</b> cộng đúng mức bạn đã nhập. Tiền OT không nằm trong package năm này vì phụ thuộc số giờ OT thực tế; xem Lớp 3.</p><p class="benefit-note" style="font-size:12.5px;margin:0 0 14px"><b>Lưu ý:</b> Đây không phải dòng tiền 12 tháng lịch kể từ ngày onboard.</p><div class="cols" id="annualcols"></div>'
rep(old_hint,new_hint,'annual hint')

# State shape and value helpers.
rep('function blank(n){return{name:n,gross:null,payType:"gross",base:"full",customBase:null,days:null,commute:null,ot:null,otPaid:"no",otFactor:null,probationEnabled:"no",probPct:null,probMon:null,probInsurance:"no",guaranteedBonusMonths:null,performanceBonusType:"months",performanceBonusValue:null,fixedAllowance:null,paidLeaveDays:null}}',
'function blank(n){return{name:n,gross:null,payType:"gross",base:"full",customBase:null,days:null,commute:null,ot:null,otPaid:"no",otFactor:null,probationEnabled:"no",probPct:null,probMon:null,probInsurance:"no",probJobType:"unknown",guaranteedBonusMonths:null,performanceBonusType:"months",performanceBonusValue:null,fixedAllowance:null,allowanceBh:"unknown",paidLeaveDays:null}}','blank shape')
rep('let dirty=false,requestSeq=0,debounceTimer=null;','let dirty=false,requestSeq=0,debounceTimer=null,activeController=null,lastRequestBody=null,lastResult=null;','request state')
rep('function hasVal(v){return v!==null&&v!==undefined&&String(v).trim()!==""&&String(v)!=="0"}\nfunction shouldOpenBenefits(o){return hasVal(o.guaranteedBonusMonths)||hasVal(o.performanceBonusValue)||hasVal(o.fixedAllowance)||hasVal(o.paidLeaveDays)}',
'''function hasInput(v){return v!==null&&v!==undefined&&String(v).trim()!==""}\nfunction hasPositiveValue(v){if(!hasInput(v))return false;const n=Number(String(v).replace(/,/g,""));return Number.isFinite(n)&&n>0}\nfunction shouldOpenBenefits(o){return hasPositiveValue(o.guaranteedBonusMonths)||hasPositiveValue(o.performanceBonusValue)||hasPositiveValue(o.fixedAllowance)||hasPositiveValue(o.paidLeaveDays)}''','value helpers')
s=s.replace('hasVal(src.probPct)||hasVal(src.probMon)','hasInput(src.probPct)||hasInput(src.probMon)')
s=s.replace('hasVal(state.sickDays)','hasPositiveValue(state.sickDays)')

old_shape=''' return{name:String(src.name||n),gross:src.gross??null,payType:src.payType==="net"?"net":"gross",base:src.base==="custom"?"custom":"full",customBase:src.customBase??null,days:src.days??null,commute:src.commute??null,ot:src.ot??null,otPaid:src.otPaid==="yes"?"yes":"no",otFactor:src.otFactor??null,\n  probationEnabled:(src.probationEnabled==="yes"||oldTrial)?"yes":"no",probPct:src.probPct??null,probMon:src.probMon??null,probInsurance:src.probInsurance==="yes"?"yes":"no",\n  guaranteedBonusMonths:src.guaranteedBonusMonths??null,performanceBonusType:src.performanceBonusType==="amount"?"amount":"months",performanceBonusValue:src.performanceBonusValue??src.targetBonusMonths??null,\n  fixedAllowance:src.fixedAllowance??null,paidLeaveDays:src.paidLeaveDays??null};'''
new_shape=''' return{name:String(src.name||n),gross:src.gross??null,payType:src.payType==="net"?"net":"gross",base:src.base==="custom"?"custom":"full",customBase:src.customBase??null,days:src.days??null,commute:src.commute??null,ot:src.ot??null,otPaid:src.otPaid==="yes"?"yes":"no",otFactor:src.otFactor??null,\n  probationEnabled:(src.probationEnabled==="yes"||oldTrial)?"yes":"no",probPct:src.probPct??null,probMon:src.probMon??null,probInsurance:src.probInsurance==="yes"?"yes":"no",probJobType:["manager","college","intermediate","other"].includes(src.probJobType)?src.probJobType:"unknown",\n  guaranteedBonusMonths:src.guaranteedBonusMonths??null,performanceBonusType:src.performanceBonusType==="amount"?"amount":"months",performanceBonusValue:src.performanceBonusValue??src.targetBonusMonths??null,\n  fixedAllowance:src.fixedAllowance??null,allowanceBh:["yes","no"].includes(src.allowanceBh)?src.allowanceBh:"unknown",paidLeaveDays:src.paidLeaveDays??null};'''
rep(old_shape,new_shape,'offer shape')
s=s.replace('["probInsurance","probationEnabled","guaranteedBonusMonths","targetBonusMonths","performanceBonusValue","fixedAllowance","paidLeaveDays","otPaid","otFactor"]','["probInsurance","probationEnabled","probJobType","guaranteedBonusMonths","targetBonusMonths","performanceBonusValue","fixedAllowance","allowanceBh","paidLeaveDays","otPaid","otFactor"]')

# Human-facing insurance option names.
s=s.replace('<button data-v="full" class="'+"'(o.base===\"full\"?\"on\":\"\")'"+'">Bằng gross</button><button data-v="custom" class="'+"'(o.base===\"custom\"?\"on\":\"\")'"+'">Khác gross</button>', '<button data-v="full" class="'+"'(o.base===\"full\"?\"on\":\"\")'"+'">Theo mặc định</button><button data-v="custom" class="'+"'(o.base===\"custom\"?\"on\":\"\")'"+'">Tự nhập</button>')

# Trial block: optional legal job group for duration validation.
old_trial='''  const trial=trialOn?'<div class="prob-wrap"><div class="duo"><div class="field"><label>Lương thử việc (% mức lương offer)</label><input type="text" data-i="'+i+'" data-k="probPct" inputmode="decimal" placeholder="vd 85" value="'+(o.probPct==null?"":esc(o.probPct))+'"></div><div class="field"><label>Số tháng thử việc</label><input type="text" data-i="'+i+'" data-k="probMon" inputmode="decimal" placeholder="vd 2" value="'+(o.probMon==null?"":esc(o.probMon))+'"></div></div><label>Trong thời gian thử việc có đóng BH bắt buộc?</label><div class="seg" data-seg="probInsurance" data-i="'+i+'"><button data-v="no" class="'+(o.probInsurance!=="yes"?"on":"")+'">Không</button><button data-v="yes" class="'+(o.probInsurance==="yes"?"on":"")+'">Có</button></div><p class="benefit-note">% thử việc được tính theo loại lương bạn đã chọn ở offer: Gross hoặc Net.</p></div>':'';'''
new_trial='''  const trial=trialOn?'<div class="prob-wrap"><div class="duo"><div class="field"><label>Lương thử việc (% mức lương offer)</label><input type="text" data-i="'+i+'" data-k="probPct" inputmode="decimal" placeholder="vd 85" value="'+(o.probPct==null?"":esc(o.probPct))+'"></div><div class="field"><label>Số tháng thử việc</label><input type="text" data-i="'+i+'" data-k="probMon" inputmode="decimal" placeholder="vd 2" value="'+(o.probMon==null?"":esc(o.probMon))+'"></div></div><div class="field"><label>Nhóm công việc <span style="font-size:11px">(để kiểm tra thời gian thử việc)</span></label><select data-i="'+i+'" data-k="probJobType"><option value="unknown" '+(o.probJobType==="unknown"?"selected":"")+'>Chưa rõ</option><option value="manager" '+(o.probJobType==="manager"?"selected":"")+'>Quản lý doanh nghiệp</option><option value="college" '+(o.probJobType==="college"?"selected":"")+'>Vị trí yêu cầu cao đẳng trở lên</option><option value="intermediate" '+(o.probJobType==="intermediate"?"selected":"")+'>Trung cấp / công nhân kỹ thuật / nhân viên nghiệp vụ</option><option value="other" '+(o.probJobType==="other"?"selected":"")+'>Công việc khác</option></select><p class="benefit-note">Giới hạn luật tương ứng: 180 ngày, 60 ngày, 30 ngày hoặc 06 ngày làm việc. Tool dùng số tháng bạn nhập để cảnh báo gần đúng; nếu hợp đồng ghi ngày, hãy ưu tiên số ngày thực tế.</p></div><label>Trong thời gian thử việc có đóng BH bắt buộc?</label><div class="seg" data-seg="probInsurance" data-i="'+i+'"><button data-v="no" class="'+(o.probInsurance!=="yes"?"on":"")+'">Không</button><button data-v="yes" class="'+(o.probInsurance==="yes"?"on":"")+'">Có</button></div><p class="benefit-note">% thử việc được tính theo loại lương bạn đã chọn ở offer: Gross hoặc Net.</p></div>':'';'''
rep(old_trial,new_trial,'trial UI')

# Allowance BH choice is explicit. Unknown uses the safer BH-included assumption unless a custom BH base is entered.
needle='''   +'<div class="duo"><div class="field suffix-row"><label>Phụ cấp cố định ngoài mức lương trên / tháng</label><input type="text" data-i="'+i+'" data-k="fixedAllowance" inputmode="numeric" placeholder="vd 1,000,000" value="'+grp(o.fixedAllowance==null?"":o.fixedAllowance)+'"><span class="suffix">đ</span></div><div class="field"><label>Nghỉ phép hưởng lương / năm</label><input type="text" data-i="'+i+'" data-k="paidLeaveDays" inputmode="decimal" placeholder="vd 12" value="'+(o.paidLeaveDays==null?"":esc(o.paidLeaveDays))+'"></div></div>'\n   +'<p class="benefit-note">Phụ cấp ở ô này được hiểu là khoản trả thêm ngoài mức lương offer, chịu thuế TNCN nhưng không tự cộng vào căn cứ BH. Nếu khoản của bạn thuộc căn cứ BH, hãy phản ánh ở ô “Mức lương làm căn cứ đóng BH”.</p>'
'''
replacement='''   +'<div class="duo"><div class="field suffix-row"><label>Phụ cấp cố định ngoài mức lương trên / tháng</label><input type="text" data-i="'+i+'" data-k="fixedAllowance" inputmode="numeric" placeholder="vd 1,000,000" value="'+grp(o.fixedAllowance==null?"":o.fixedAllowance)+'"><span class="suffix">đ</span></div><div class="field"><label>Nghỉ phép hưởng lương / năm</label><input type="text" data-i="'+i+'" data-k="paidLeaveDays" inputmode="decimal" placeholder="vd 12" value="'+(o.paidLeaveDays==null?"":esc(o.paidLeaveDays))+'"></div></div>'\n   +'<div class="field"><label>Phụ cấp này có tính vào căn cứ BH?</label><div class="seg" data-seg="allowanceBh" data-i="'+i+'"><button data-v="unknown" class="'+(o.allowanceBh==="unknown"?"on":"")+'">Chưa rõ</button><button data-v="yes" class="'+(o.allowanceBh==="yes"?"on":"")+'">Có</button><button data-v="no" class="'+(o.allowanceBh==="no"?"on":"")+'">Không</button></div><p class="benefit-note">Nếu để “Chưa rõ”, tool tạm tính <b>Có</b> để tránh làm tiền về tay trông cao hơn thực tế. Nếu bạn chọn “Tự nhập” mức căn cứ BH ở phía trên, mức tự nhập luôn được ưu tiên.</p></div>'
'''
rep(needle,replacement,'allowance BH UI')

# Clarify the default BH behavior below the two offers.
s=s.replace('<b>Chưa biết mức đóng bảo hiểm?</b> Có thể hỏi HR: “Mức lương làm căn cứ đóng BHXH/BHYT/BHTN của vị trí này là bao nhiêu?”. Nếu tổng gross có khoản không thuộc căn cứ đóng BH, mức này có thể khác gross.', '<b>Chưa biết mức đóng bảo hiểm?</b> Có thể hỏi HR: “Mức lương làm căn cứ đóng BHXH/BHYT/BHTN của vị trí này là bao nhiêu?”. “Theo mặc định” dùng gross và tạm cộng phụ cấp cố định vào căn cứ BH nếu bạn chưa xác nhận là “Không”; nếu HR đưa một mức BH riêng, chọn “Tự nhập”.')

# Offer-level select handling and allowance toggle.
old_input='''host.addEventListener("input",function(e){\n const el=e.target,iRaw=el.getAttribute("data-i"),k=el.getAttribute("data-k");if(iRaw==null||!k)return;const i=parseInt(iRaw,10);'''
new_input='''host.addEventListener("input",function(e){\n const el=e.target;if(el.tagName==="SELECT")return;const iRaw=el.getAttribute("data-i"),k=el.getAttribute("data-k");if(iRaw==null||!k)return;const i=parseInt(iRaw,10);'''
rep(old_input,new_input,'offer input select skip')
insert='''});\nhost.addEventListener("change",function(e){const el=e.target;if(el.tagName!=="SELECT")return;const iRaw=el.getAttribute("data-i"),k=el.getAttribute("data-k");if(iRaw==null||!k)return;state.offers[parseInt(iRaw,10)][k]=el.value;markDirty();scheduleCalculation()});\nhost.addEventListener("click",function(e){'''
rep('});\nhost.addEventListener("click",function(e){',insert,'offer select handler')
rep(' if(kind==="probationEnabled"){state.offers[i].probationEnabled=v;markDirty();renderInputs();scheduleCalculation();return}', ' if(kind==="allowanceBh"){state.offers[i].allowanceBh=v;[].forEach.call(seg.children,x=>x.classList.toggle("on",x===b));markDirty();scheduleCalculation();return}\n if(kind==="probationEnabled"){state.offers[i].probationEnabled=v;markDirty();renderInputs();scheduleCalculation();return}','allowance segment')

# Request optimization: no call for empty form, debounce, cache identical state, abort stale request.
old_calc='''function showApiError(){const e=document.getElementById("empty");e.style.display="";e.textContent="Không kết nối được máy tính phía server. Thử tải lại trang sau ít phút.";document.getElementById("results").classList.add("hidden")}\nasync function calculateNow(){const seq=++requestSeq;try{const res=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(state),cache:"no-store"});if(!res.ok)throw new Error("HTTP "+res.status);const data=await res.json();if(seq!==requestSeq)return null;applyResult(data);return data}catch(e){if(seq===requestSeq)showApiError();return null}}\nfunction scheduleCalculation(){clearTimeout(debounceTimer);debounceTimer=setTimeout(calculateNow,180)}'''
new_calc='''function showApiError(msg){const e=document.getElementById("empty");e.style.display="";e.textContent=msg||"Không kết nối được máy chủ tính toán. Thử tải lại trang sau ít phút.";document.getElementById("results").classList.add("hidden")}\nfunction hasAnySalary(){return state.offers.some(o=>{const n=Number(String(o.gross??"").replace(/,/g,""));return Number.isFinite(n)&&n>0})}\nasync function calculateNow(){\n clearTimeout(debounceTimer);\n if(!hasAnySalary()){if(activeController)activeController.abort();activeController=null;lastRequestBody=null;lastResult=null;applyResult({hasResults:false});return null}\n const body=JSON.stringify(state);\n if(body===lastRequestBody&&lastResult){applyResult(lastResult);return lastResult}\n if(activeController)activeController.abort();\n const controller=new AbortController();activeController=controller;const seq=++requestSeq;\n try{\n  const res=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body,cache:"no-store",signal:controller.signal});\n  if(res.status===429){if(seq===requestSeq)showApiError("Đang có nhiều lượt tính toán cùng lúc. Chờ khoảng một phút rồi thử lại.");return null}\n  if(!res.ok)throw new Error("HTTP "+res.status);\n  const data=await res.json();if(seq!==requestSeq)return null;lastRequestBody=body;lastResult=data;applyResult(data);return data\n }catch(e){if(e&&e.name==="AbortError")return null;if(seq===requestSeq)showApiError();return null}\n finally{if(activeController===controller)activeController=null}\n}\nfunction scheduleCalculation(){clearTimeout(debounceTimer);debounceTimer=setTimeout(calculateNow,600)}'''
rep(old_calc,new_calc,'request optimization')

# Clear cache when wiping all data.
s=s.replace('syncCtx();renderInputs();renderSwitchingInputs();dirty=false;updateSaveUI();calculateNow()', 'syncCtx();renderInputs();renderSwitchingInputs();lastRequestBody=null;lastResult=null;if(activeController)activeController.abort();activeController=null;dirty=false;updateSaveUI();calculateNow()',1)

# Add referrer policy now; CSP is inserted after the final script hash is known.
rep('<meta name="viewport" content="width=device-width, initial-scale=1.0" />','<meta name="viewport" content="width=device-width, initial-scale=1.0" />\n<meta name="referrer" content="no-referrer" />','referrer meta')

# Compute CSP hash of the final inline script and insert a defense-in-depth policy that blocks inline event handlers.
start=s.index('<script>')+len('<script>');end=s.index('</script>',start)
script=s[start:end]
digest=base64.b64encode(hashlib.sha256(script.encode('utf-8')).digest()).decode('ascii')
csp=("<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'self'; "
     f"script-src 'sha256-{digest}'; script-src-attr 'none'; "
     "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; "
     "connect-src https://linkedin-tools-api-test.vercel.app; img-src 'self' data:; object-src 'none'; base-uri 'none'; form-action 'none'\" />")
s=s.replace('<meta name="referrer" content="no-referrer" />','<meta name="referrer" content="no-referrer" />\n'+csp,1)
p.write_text(s)
