const API_URL='https://linkedin-tools-api-test.vercel.app/api/mba-plan';
const STORAGE_KEY='mba_core_m1_v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const MODEL_META={
  food:{label:'Bán đồ ăn / đồ uống',title:'Thiết lập nguồn đồ ăn / đồ uống',text:'Chọn cách MBA nên gọi một lượt bán và các kênh bạn đang hoặc dự định dùng.'},
  goods:{label:'Bán hàng hóa',title:'Thiết lập nguồn bán hàng hóa',text:'Kênh bán được lưu như thuộc tính của nguồn thu, không phải một mô hình kinh doanh riêng.'},
  service:{label:'Bán dịch vụ',title:'Thiết lập nguồn dịch vụ',text:'Cách tính tiền quyết định đơn vị MBA sẽ dùng cho hòa vốn, mục tiêu và khả năng phục vụ.'},
  mmo:{label:'MMO / Kiếm tiền từ lượt truy cập và người xem',title:'Thiết lập nguồn MMO',text:'Chọn cách nguồn này tạo tiền. MBA chỉ giữ thuật ngữ quen dùng như Affiliate khi cần thiết.'},
  digital:{label:'Sản phẩm số - bán một lần',title:'Thiết lập nguồn sản phẩm số',text:'Nguồn này thu tiền theo từng lượt mua, không dùng logic thu phí định kỳ.'},
  recurring:{label:'Thu phí định kỳ',title:'Thiết lập nguồn thu định kỳ',text:'Chu kỳ thu tiền được lưu để MBA quy đổi và tính đúng ở bước lập kế hoạch.'},
  other:{label:'Khác / Tự nhập',title:'Tự mô tả nguồn thu',text:'Hãy cho MBA biết nguồn này kiếm tiền theo cách nào và bạn muốn gọi một đơn vị tạo tiền là gì.'}
};
let state=loadState(),draftName='',draftStream=null,editingStreamId=null,planningStreamId=null;
function defaultState(){return{version:1,currentProfileId:null,profiles:[]}}
function loadState(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));return x&&x.version===1?x:defaultState()}catch(e){return defaultState()}}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));syncHeader()}
function uid(prefix){return prefix+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function now(){return new Date().toISOString()}
function currentProfile(){return state.profiles.find(p=>p.id===state.currentProfileId)||null}
function currentStream(){const p=currentProfile();return p?.streams.find(s=>s.id===planningStreamId)||null}
function go(id){$$('.screen').forEach(x=>x.classList.remove('on'));$('#'+id)?.classList.add('on');syncHeader();window.scrollTo(0,0)}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('on');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('on'),2400)}
function syncHeader(){const p=currentProfile();$('#profilePill').textContent=p?p.name:'Chưa có hồ sơ'}
function startPlanning(){if(state.profiles.length)openProfiles();else newProfile()}
function journeyNotReady(name){if(state.profiles.length){openProfiles();toast(name+' sẽ dùng chính các hồ sơ này ở milestone sau.')}else{toast('Hãy tạo Hồ sơ kinh doanh trước.');newProfile()}}
function openProfiles(){renderProfiles();go('profiles')}
function renderProfiles(){const host=$('#profileList');if(!state.profiles.length){host.innerHTML='<div class="emptyState">Chưa có hồ sơ nào. Tạo hồ sơ đầu tiên để MBA bắt đầu hiểu việc kinh doanh của bạn.</div>';return}host.innerHTML=state.profiles.slice().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(p=>{const planned=p.streams.filter(s=>s.planning?.result?.status==='ok').length;return`<div class="profileCard"><h3>${esc(p.name)}</h3><p>${p.streams.length} nguồn thu · ${planned}/${p.streams.length} nguồn đã có kế hoạch nhanh · cập nhật ${formatDate(p.updatedAt)}</p><div class="actions"><button class="btn secondary" onclick="openProfile('${p.id}')">Mở hồ sơ</button><button class="btn danger" onclick="deleteProfile('${p.id}')">Xóa</button></div></div>`}).join('')}
function newProfile(){state.currentProfileId=null;draftName='';draftStream=null;editingStreamId=null;$('#newProfileName').value='';go('newProfile')}
function backFromNewProfile(){state.profiles.length?openProfiles():go('landing')}
function continueToFirstSource(){const name=$('#newProfileName').value.trim();if(!name){toast('Nhập tên việc kinh doanh / dự án trước khi tiếp tục.');$('#newProfileName').focus();return}draftName=name;editingStreamId=null;go('modelRouter')}
function backFromRouter(){currentProfile()?go('builder'):go('newProfile')}
function selectModel(model){draftStream={model,config:{}};renderStreamSetup();go('streamSetup')}
function renderStreamSetup(){const meta=MODEL_META[draftStream.model];$('#streamSetupTitle').textContent=meta.title;$('#streamSetupText').textContent=meta.text;$('#streamName').value=draftStream.name||'';$('#dynamicFields').innerHTML=fieldsForModel(draftStream.model,draftStream.config||{});bindChoices()}
function fieldsForModel(model,c){if(model==='food')return choiceBlock('Đơn vị MBA dùng cho một lượt bán','foodUnit',[['đơn','Đơn'],['bill','Bill'],['khách','Khách'],['custom','Khác / Tự nhập']],c.unit)+customInput('foodUnitCustom','Bạn muốn gọi đơn vị này là gì?',c.unitCustom,'Ví dụ: bàn, set, suất')+multiBlock('Kênh bán','foodChannels',[['store','Tại quán'],['takeaway','Mang đi'],['grab','GrabFood'],['shopeefood','ShopeeFood'],['custom','Khác / Tự nhập']],c.channels)+customInput('foodChannelCustom','Tên kênh khác',c.channelCustom,'Ví dụ: hotline, Zalo');
if(model==='goods')return multiBlock('Kênh bán','goodsChannels',[['store','Cửa hàng'],['shopee','Shopee'],['tiktok','TikTok Shop'],['social','Facebook / Instagram'],['website','Website'],['custom','Khác / Tự nhập']],c.channels)+customInput('goodsChannelCustom','Tên kênh khác',c.channelCustom,'Ví dụ: đại lý, livestream riêng');
if(model==='service')return choiceBlock('Bạn thường tính tiền dịch vụ theo cách nào?','serviceBasis',[['visit','Theo lượt / buổi'],['hour','Theo giờ / ngày công'],['project','Theo dự án'],['client','Theo khách hàng định kỳ'],['custom','Khác / Tự nhập']],c.basis)+customInput('serviceBasisCustom','Bạn gọi một đơn vị bán dịch vụ là gì?',c.basisCustom,'Ví dụ: ca, phiên, hợp đồng, gói');
if(model==='mmo')return choiceBlock('Nguồn MMO này tạo tiền chủ yếu bằng cách nào?','mmoType',[['affiliate','Affiliate'],['content','Nội dung / tài trợ'],['ads','Quảng cáo website / app'],['lead','Tạo khách hàng tiềm năng'],['custom','Khác / Tự nhập']],c.type)+customInput('mmoTypeCustom','Mô tả cách kiếm tiền',c.typeCustom,'Ví dụ: bán quyền truy cập dữ liệu');
if(model==='digital')return multiBlock('Kênh bán chính','digitalChannels',[['website','Website riêng'],['platform','Nền tảng bán sản phẩm số'],['social','Mạng xã hội'],['market','Sàn / chợ sản phẩm số'],['custom','Khác / Tự nhập']],c.channels)+customInput('digitalChannelCustom','Tên kênh khác',c.channelCustom,'Ví dụ: nền tảng riêng của đối tác');
if(model==='recurring')return choiceBlock('Bạn thu phí theo chu kỳ nào?','billing',[['month','Theo tháng'],['year','Theo năm'],['both','Có cả tháng và năm'],['custom','Khác / Tự nhập']],c.billing)+customInput('billingCustom','Chu kỳ của bạn là bao nhiêu tháng?',c.billingCustom,'Ví dụ: 3');
return '<div class="field"><label>Mô tả cách nguồn này kiếm tiền</label><textarea id="otherDescription" placeholder="Ví dụ: nhận phí khi kết nối thành công người mua với nhà cung cấp">'+esc(c.description||'')+'</textarea></div><div class="field"><label>Bạn muốn MBA gọi một đơn vị tạo tiền là gì?</label><input id="otherUnit" value="'+escAttr(c.unit||'')+'" placeholder="Ví dụ: hợp đồng, lượt kết nối, phiên"></div>'}
function choiceBlock(label,id,items,selected){return`<div class="field"><label>${label}</label><div class="choiceGrid" data-choice="${id}">${items.map(([v,t])=>`<button type="button" class="choice ${selected===v?'selected':''}" data-value="${v}">${t}</button>`).join('')}</div></div>`}
function multiBlock(label,id,items,selected=[]){const arr=selected||[];return`<div class="field"><label>${label}</label><div class="choiceGrid" data-multi="${id}">${items.map(([v,t])=>`<button type="button" class="choice ${arr.includes(v)?'selected':''}" data-value="${v}">${t}</button>`).join('')}</div></div>`}
function customInput(id,label,value,placeholder){return`<div class="field customArea" id="${id}Wrap"><label>${label}</label><input id="${id}" value="${escAttr(value||'')}" placeholder="${placeholder}"></div>`}
function bindChoices(){$$('[data-choice] .choice').forEach(b=>b.onclick=()=>{const p=b.closest('[data-choice]');p.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');refreshCustomVisibility()});$$('[data-multi] .choice').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');refreshCustomVisibility()});refreshCustomVisibility()}
function refreshCustomVisibility(){toggleCustom('foodUnit','foodUnitCustomWrap');toggleCustomMulti('foodChannels','foodChannelCustomWrap');toggleCustomMulti('goodsChannels','goodsChannelCustomWrap');toggleCustom('serviceBasis','serviceBasisCustomWrap');toggleCustom('mmoType','mmoTypeCustomWrap');toggleCustomMulti('digitalChannels','digitalChannelCustomWrap');toggleCustom('billing','billingCustomWrap')}
function toggleCustom(choiceId,wrapId){const wrap=$('#'+wrapId);if(!wrap)return;const selected=$(`[data-choice="${choiceId}"] .choice.selected`)?.dataset.value;wrap.classList.toggle('on',selected==='custom')}
function toggleCustomMulti(choiceId,wrapId){const wrap=$('#'+wrapId);if(!wrap)return;const selected=$(`[data-multi="${choiceId}"] .choice[data-value="custom"]`)?.classList.contains('selected');wrap.classList.toggle('on',!!selected)}
function readChoice(id){return $(`[data-choice="${id}"] .choice.selected`)?.dataset.value||''}
function readMulti(id){return $$(`[data-multi="${id}"] .choice.selected`).map(x=>x.dataset.value)}
function collectConfig(model){if(model==='food')return{unit:readChoice('foodUnit'),unitCustom:val('foodUnitCustom'),channels:readMulti('foodChannels'),channelCustom:val('foodChannelCustom')};if(model==='goods')return{channels:readMulti('goodsChannels'),channelCustom:val('goodsChannelCustom')};if(model==='service')return{basis:readChoice('serviceBasis'),basisCustom:val('serviceBasisCustom')};if(model==='mmo')return{type:readChoice('mmoType'),typeCustom:val('mmoTypeCustom')};if(model==='digital')return{channels:readMulti('digitalChannels'),channelCustom:val('digitalChannelCustom')};if(model==='recurring')return{billing:readChoice('billing'),billingCustom:val('billingCustom')};return{description:val('otherDescription'),unit:val('otherUnit')}}
function validateConfig(model,c){if(model==='food'){if(!c.unit)return'Chọn cách MBA gọi một lượt bán.';if(c.unit==='custom'&&!c.unitCustom)return'Nhập tên đơn vị bạn muốn dùng.';if(!c.channels.length)return'Chọn ít nhất một kênh bán.';if(c.channels.includes('custom')&&!c.channelCustom)return'Nhập tên kênh khác.'}if(model==='goods'){if(!c.channels.length)return'Chọn ít nhất một kênh bán.';if(c.channels.includes('custom')&&!c.channelCustom)return'Nhập tên kênh khác.'}if(model==='service'){if(!c.basis)return'Chọn cách bạn thường tính tiền dịch vụ.';if(c.basis==='custom'&&!c.basisCustom)return'Nhập đơn vị bán dịch vụ của bạn.'}if(model==='mmo'){if(!c.type)return'Chọn cách nguồn MMO này tạo tiền.';if(c.type==='custom'&&!c.typeCustom)return'Mô tả cách kiếm tiền của nguồn này.'}if(model==='digital'){if(!c.channels.length)return'Chọn ít nhất một kênh bán.';if(c.channels.includes('custom')&&!c.channelCustom)return'Nhập tên kênh khác.'}if(model==='recurring'){if(!c.billing)return'Chọn chu kỳ thu phí.';if(c.billing==='custom'&&(!c.billingCustom||Number(c.billingCustom)<=0))return'Nhập số tháng trong một chu kỳ.'}if(model==='other'&&(!c.description||!c.unit))return'Mô tả cách kiếm tiền và đơn vị tạo tiền.';return''}
function saveStream(){const name=$('#streamName').value.trim();if(!name){toast('Nhập tên nguồn thu.');return}const config=collectConfig(draftStream.model),error=validateConfig(draftStream.model,config);if(error){toast(error);return}let p=currentProfile();if(!p){p={id:uid('profile'),name:draftName,status:'draft',currency:'VND',createdAt:now(),updatedAt:now(),sharedCosts:[],streams:[]};state.profiles.push(p);state.currentProfileId=p.id}const old=editingStreamId?p.streams.find(x=>x.id===editingStreamId):null;const stream={id:editingStreamId||uid('stream'),name,model:draftStream.model,config,status:'structured',planning:old?.planning||null,createdAt:old?.createdAt||now(),updatedAt:now()};if(editingStreamId){const i=p.streams.findIndex(x=>x.id===editingStreamId);p.streams[i]=stream}else p.streams.push(stream);p.updatedAt=now();persist();editingStreamId=null;draftStream=null;renderBuilder();go('builder');toast('Đã tự động lưu nguồn thu trên thiết bị.')}
function renderBuilder(){const p=currentProfile();if(!p)return openProfiles();$('#builderName').textContent=p.name;const planned=p.streams.filter(s=>s.planning?.result?.status==='ok').length;$('#builderMeta').textContent=p.streams.length+' nguồn thu · '+planned+'/'+p.streams.length+' nguồn đã có kế hoạch nhanh';$('#sourceList').innerHTML=p.streams.map((s,i)=>{const has=s.planning?.result?.status==='ok',profit=s.planning?.result?.summary?.monthlyProfit;return`<div class="sourceCard"><div class="sourceTop"><div><div class="eyebrow">Nguồn ${String(i+1).padStart(2,'0')}</div><h3>${esc(s.name)}</h3><div class="sourceModel">${esc(MODEL_META[s.model].label)}</div></div></div><div class="sourceSummary">${esc(summaryFor(s))}</div><div class="planBadge ${has?'':'empty'}">${has?'✓ Đã có kế hoạch nhanh'+(Number.isFinite(profit)?' · lợi nhuận '+formatMoney(profit):''):'Chưa nhập số liệu kế hoạch'}</div><div class="sourceActions"><button onclick="openPlanning('${s.id}')">${has?'Cập nhật số liệu':'Nhập số liệu'}</button><button onclick="editSource('${s.id}')">Chỉnh cấu trúc</button><button class="delete" onclick="deleteSource('${s.id}')">Xóa nguồn thu</button></div></div>`}).join('')}
function summaryFor(s){const c=s.config||{};if(s.model==='food')return'Đơn vị: '+labelFoodUnit(c)+' · Kênh: '+labelsChannels(c.channels,c.channelCustom,'food').join(', ');if(s.model==='goods')return'Kênh: '+labelsChannels(c.channels,c.channelCustom,'goods').join(', ');if(s.model==='service')return'Tính tiền: '+labelService(c);if(s.model==='mmo')return'Cách tạo tiền: '+labelMmo(c);if(s.model==='digital')return'Kênh: '+labelsDigital(c.channels,c.channelCustom).join(', ');if(s.model==='recurring')return'Chu kỳ: '+labelBilling(c);return'Đơn vị: '+(c.unit||'tự nhập')+' · '+(c.description||'')}
function labelFoodUnit(c){return c.unit==='đơn'?'đơn':c.unit==='bill'?'bill':c.unit==='khách'?'khách':c.unitCustom||'đơn vị'}
function labelsChannels(arr=[],custom,kind){const food={store:'Tại quán',takeaway:'Mang đi',grab:'GrabFood',shopeefood:'ShopeeFood'},goods={store:'Cửa hàng',shopee:'Shopee',tiktok:'TikTok Shop',social:'Facebook / Instagram',website:'Website'};const map=kind==='food'?food:goods;return arr.map(x=>x==='custom'?(custom||'Khác'):(map[x]||x))}
function labelsDigital(arr=[],custom){const map={website:'Website riêng',platform:'Nền tảng bán sản phẩm số',social:'Mạng xã hội',market:'Sàn / chợ sản phẩm số'};return arr.map(x=>x==='custom'?(custom||'Khác'):(map[x]||x))}
function labelService(c){return c.basis==='visit'?'Theo lượt / buổi':c.basis==='hour'?'Theo giờ / ngày công':c.basis==='project'?'Theo dự án':c.basis==='client'?'Theo khách hàng định kỳ':c.basisCustom||'Tự nhập'}
function labelMmo(c){return c.type==='affiliate'?'Affiliate':c.type==='content'?'Nội dung / tài trợ':c.type==='ads'?'Quảng cáo website / app':c.type==='lead'?'Tạo khách hàng tiềm năng':c.typeCustom||'Tự nhập'}
function labelBilling(c){return c.billing==='month'?'Theo tháng':c.billing==='year'?'Theo năm':c.billing==='both'?'Cả tháng và năm':(c.billingCustom?c.billingCustom+' tháng / chu kỳ':'Tự nhập')}
function addSource(){editingStreamId=null;draftStream=null;go('modelRouter')}
function editSource(id){const p=currentProfile(),s=p?.streams.find(x=>x.id===id);if(!s)return;editingStreamId=id;draftStream={model:s.model,config:JSON.parse(JSON.stringify(s.config||{})),name:s.name};renderStreamSetup();go('streamSetup')}
function deleteSource(id){const p=currentProfile();if(!p||!confirm('Xóa nguồn thu này khỏi hồ sơ?'))return;p.streams=p.streams.filter(x=>x.id!==id);p.status='draft';p.updatedAt=now();persist();if(!p.streams.length){toast('Hồ sơ chưa còn nguồn thu nào.');addSource();return}renderBuilder();toast('Đã xóa nguồn thu.')}
function openProfile(id){state.currentProfileId=id;persist();renderBuilder();go('builder')}
function openCurrentBuilder(){const p=currentProfile();if(p){renderBuilder();go('builder')}else openProfiles()}
function deleteProfile(id){const p=state.profiles.find(x=>x.id===id);if(!p||!confirm('Xóa hồ sơ “'+p.name+'” và toàn bộ nguồn thu đã lưu trên thiết bị?'))return;state.profiles=state.profiles.filter(x=>x.id!==id);if(state.currentProfileId===id)state.currentProfileId=null;persist();renderProfiles();toast('Đã xóa hồ sơ.')}
function finishStructure(){const p=currentProfile();if(!p||!p.streams.length){toast('Cần ít nhất một nguồn thu.');return}p.status='active';p.updatedAt=now();persist();const planned=p.streams.filter(s=>s.planning?.result?.status==='ok').length;$('#readyName').textContent=p.name;$('#readyStreams').textContent=p.streams.length;$('#readyPlanned').textContent=planned+'/'+p.streams.length;go('ready')}

function openPlanning(id){planningStreamId=id;const s=currentStream();if(!s)return;$('#planEyebrow').textContent=MODEL_META[s.model].label;$('#planTitle').textContent=s.name;$('#planIntro').textContent=planIntro(s);$('#planFields').innerHTML=planFields(s,s.planning?.input||{});bindPlanUI();go('plan')}
function planIntro(s){if(s.model==='food')return'Nhập 5 số cốt lõi để MBA tính lợi nhuận, phần còn lại trên mỗi '+labelFoodUnit(s.config)+' và mức bán cần để hòa vốn.';if(s.model==='goods')return'Bắt đầu bằng số bình quân. Chi phí do hoàn đơn và cấu trúc phí từng kênh sẽ được tách ở chế độ tính chi tiết.';if(s.model==='service')return'MBA dùng đúng đơn vị dịch vụ bạn đã chọn và có thể kiểm tra thêm giới hạn khả năng phục vụ.';if(s.model==='mmo')return'Các câu hỏi thay đổi theo cách nguồn MMO này tạo tiền.';if(s.model==='digital')return'Bản nhanh tách lượt mua, hoàn tiền và chi phí hàng tháng.';if(s.model==='recurring')return'MBA quy đổi các chu kỳ thu phí về tháng để bạn nhìn sức khỏe mô hình trên cùng một đơn vị.';return'Nhập số tiền trên mỗi đơn vị, sản lượng và chi phí tháng.'}
function moneyField(key,label,value,placeholder,helper=''){return`<div class="field"><label>${label}</label><div class="amount"><input class="money" data-plan-key="${key}" inputmode="numeric" value="${moneyInputValue(value)}" placeholder="${placeholder}"><span>đ</span></div>${helper?`<div class="hint">${helper}</div>`:''}</div>`}
function numberField(key,label,value,placeholder,suffix='',helper=''){return`<div class="field"><label>${label}</label><div class="amount"><input data-plan-key="${key}" type="number" inputmode="decimal" value="${value??''}" placeholder="${placeholder}">${suffix?`<span>${suffix}</span>`:''}</div>${helper?`<div class="hint">${helper}</div>`:''}</div>`}
function targetField(value){return moneyField('targetProfit','Bạn muốn đạt khoảng bao nhiêu lợi nhuận mỗi tháng? (không bắt buộc)',value,'20,000,000','Để trống nếu bạn chỉ muốn xem hòa vốn và kết quả theo mức bán dự kiến.')}
function planFields(s,input){const c=s.config||{};if(s.model==='food'){const u=labelFoodUnit(c);return'<div class="modeNote"><b>Nhập nhanh</b> - MBA dùng số bình quân để cho bạn kết quả đầu tiên. Các kênh bán đã lưu: '+esc(labelsChannels(c.channels,c.channelCustom,'food').join(', '))+'.</div>'+moneyField('price','Khách trả trung bình cho một '+u,input.price,'50,000')+moneyField('directCost','Chi phí trực tiếp cho một '+u,input.directCost,'20,000','Ví dụ: nguyên liệu, bao bì, phí thanh toán và phần ship phát sinh theo '+u+'.')+numberField('dailyVolume','Dự kiến bán trung bình mỗi ngày',input.dailyVolume,'40',u+'/ngày')+numberField('daysPerMonth','Số ngày bán mỗi tháng',input.daysPerMonth,'30','ngày/tháng')+moneyField('fixedCosts','Tổng chi phí hàng tháng',input.fixedCosts,'34,000,000','Các khoản vẫn phải trả dù bán nhiều hay ít.')+targetField(input.targetProfit)}
if(s.model==='goods')return'<div class="modeNote"><b>Nhập nhanh</b> - tổng hợp các chi phí trực tiếp vào một con số/đơn. Kênh bán: '+esc(labelsChannels(c.channels,c.channelCustom,'goods').join(', '))+'.</div>'+moneyField('price','Giá trị trung bình một đơn thành công',input.price,'250,000')+moneyField('directCost','Tổng chi phí trực tiếp trên một đơn thành công',input.directCost,'165,000','Giá nhập/sản xuất, đóng gói, hỗ trợ ship, phí kênh bán, thanh toán, affiliate...')+numberField('ordersPerMonth','Số đơn được đặt mỗi tháng',input.ordersPerMonth,'500','đơn/tháng')+numberField('returnRate','Tỷ lệ hoàn / hủy',input.returnRate,'8','%')+moneyField('fixedCosts','Tổng chi phí hàng tháng',input.fixedCosts,'30,000,000')+targetField(input.targetProfit);
if(s.model==='service')return servicePlanFields(s,input);
if(s.model==='mmo')return mmoPlanFields(s,input);
if(s.model==='digital')return'<div class="modeNote"><b>Nhập nhanh</b> - sản phẩm số bán một lần, không dùng logic thuê bao.</div>'+moneyField('price','Giá bán trung bình',input.price,'499,000')+moneyField('directCost','Chi phí trực tiếp trên một lượt bán thực nhận',input.directCost,'50,000','Ví dụ: phí nền tảng, thanh toán, affiliate, support phát sinh theo lượt bán.')+numberField('purchases','Số lượt mua mỗi tháng',input.purchases,'100','lượt/tháng')+numberField('refundRate','Tỷ lệ hoàn tiền',input.refundRate,'5','%')+moneyField('fixedCosts','Tổng chi phí hàng tháng',input.fixedCosts,'12,000,000')+targetField(input.targetProfit);
if(s.model==='recurring')return recurringPlanFields(s,input);
return genericPlanFields(s,input)}
function servicePlanFields(s,input){const c=s.config||{},u=serviceUnit(c),cap=input.capacity||{},basis=c.basis;let capacityChoices=[['none','Không cần tính','Chỉ tính lời, lỗ và hòa vốn'],['known','Có - tôi biết mức tối đa','Nhập mức tối đa có thể phục vụ mỗi tháng']];if(['visit','hour','project','client'].includes(basis))capacityChoices.push(['estimate','Có - giúp tôi ước tính','MBA hỏi theo loại dịch vụ để ước tính']);capacityChoices.push(['custom','Khác / Tự nhập','Tự đặt chỉ số giới hạn và cùng đơn vị ở mức dùng/tối đa']);let html='<div class="modeNote"><b>Nhập nhanh</b> - đơn vị đang dùng: <b>'+esc(u)+'</b>. MBA sẽ không bắt bạn nhập lại dữ liệu đã biết.</div>'+moneyField('price','Khách trả trung bình cho một '+u,input.price,'1,000,000')+moneyField('directCost','Chi phí trực tiếp cho một '+u,input.directCost,'200,000')+numberField('volume','Số '+u+' dự kiến mỗi tháng',input.volume,'40',u+'/tháng')+moneyField('fixedCosts','Tổng chi phí hàng tháng',input.fixedCosts,'20,000,000')+targetField(input.targetProfit)+planChoiceBlock('Business có giới hạn số '+u+' có thể phục vụ không?','capacity.mode',capacityChoices,cap.mode||'none');
html+=`<div data-cap-section="known" class="customArea">${numberField('capacity.max','Tối đa có thể phục vụ mỗi tháng',cap.max,'60',u+'/tháng')}</div>`;
html+=`<div data-cap-section="estimate" class="customArea">${estimateCapacityFields(c,cap)}</div>`;
html+=`<div data-cap-section="custom" class="customArea"><div class="field"><label>Tên giới hạn bạn muốn theo dõi</label><input data-plan-key="capacity.label" value="${escAttr(cap.label||'')}" placeholder="Ví dụ: slot tư vấn, giờ phòng máy"></div>${numberField('capacity.usage','Mức dự kiến sử dụng',cap.usage,'120','')}${numberField('capacity.max','Mức tối đa',cap.max,'160','')}<div class="hint">Hai số trên phải dùng cùng một đơn vị. MBA chỉ tính tỷ lệ giữa chúng, không tự suy đoán cách quy đổi.</div></div>`;return html}
function estimateCapacityFields(c,cap){let x='';if(c.basis==='visit')x+=numberField('capacity.people','Số người trực tiếp phục vụ',cap.people,'3','người')+numberField('capacity.unitsPerPersonPerDay','Một người phục vụ khoảng bao nhiêu '+serviceUnit(c)+' mỗi ngày',cap.unitsPerPersonPerDay,'5',serviceUnit(c)+'/người/ngày')+numberField('capacity.workDays','Số ngày làm mỗi tháng',cap.workDays,'26','ngày/tháng');if(c.basis==='hour')x+=numberField('capacity.people','Số người trực tiếp tạo doanh thu',cap.people,'2','người')+numberField('capacity.hoursPerDay','Giờ làm mỗi người mỗi ngày',cap.hoursPerDay,'8','giờ/ngày')+numberField('capacity.workDays','Số ngày làm mỗi tháng',cap.workDays,'22','ngày/tháng');if(c.basis==='project')x+=numberField('capacity.parallelProjects','Số dự án có thể xử lý song song',cap.parallelProjects,'6','dự án')+numberField('capacity.avgProjectMonths','Một dự án kéo dài trung bình',cap.avgProjectMonths,'2','tháng');if(c.basis==='client')x+=numberField('capacity.people','Số người phụ trách khách',cap.people,'3','người')+numberField('capacity.clientsPerPerson','Một người chăm tối đa',cap.clientsPerPerson,'8','khách/người');const vals=c.basis==='hour'?[60,70,80]:[70,80,90];x+=`<div class="field"><label>Mức vận hành thực tế dùng để tính</label><div class="choiceGrid" data-plan-choice="capacity.realisticPreset">${vals.map(v=>`<button type="button" class="choice ${(cap.realisticPreset||String(vals[1]))===String(v)?'selected':''}" data-value="${v}">${v}%${v===vals[1]?'<small>Mức tham khảo</small>':''}</button>`).join('')}<button type="button" class="choice ${cap.realisticPreset==='custom'?'selected':''}" data-value="custom">Tự nhập</button></div><div data-realistic-custom class="customArea">${numberField('capacity.realisticPct','Tỷ lệ bạn muốn dùng',cap.realisticPct,'85','%')}</div></div>`;return x}
function mmoPlanFields(s,input){const t=s.config?.type||'custom';if(t==='affiliate')return'<div class="modeNote"><b>Affiliate</b> - MBA dùng chuyển đổi làm đơn vị tạo tiền.</div>'+numberField('conversions','Số chuyển đổi dự kiến mỗi tháng',input.conversions,'500','chuyển đổi/tháng')+moneyField('revenuePerConversion','Hoa hồng trung bình mỗi chuyển đổi',input.revenuePerConversion,'65,000')+moneyField('fixedCosts','Tổng chi phí hàng tháng',input.fixedCosts,'23,000,000')+targetField(input.targetProfit);if(t==='content')return'<div class="modeNote"><b>Nội dung / tài trợ</b> - tách khoản thu nền tảng và booking/tài trợ để tránh gom mọi thứ thành một con số.</div>'+moneyField('platformRevenue','Khoản thu từ nền tảng mỗi tháng',input.platformRevenue,'8,000,000')+numberField('deals','Số booking / tài trợ mỗi tháng',input.deals,'4','booking/tháng')+moneyField('revenuePerDeal','Mức thu trung bình mỗi booking / tài trợ',input.revenuePerDeal,'5,000,000')+moneyField('directCostPerDeal','Chi phí trực tiếp mỗi booking / tài trợ',input.directCostPerDeal,'500,000')+moneyField('fixedCosts','Tổng chi phí hàng tháng',input.fixedCosts,'12,000,000');if(t==='ads')return'<div class="modeNote"><b>Quảng cáo website / app</b> - dùng lượt có thể kiếm tiền và số tiền thu trên 1.000 lượt.</div>'+numberField('views','Lượt xem / hiển thị có thể kiếm tiền mỗi tháng',input.views,'1000000','lượt/tháng')+moneyField('revenuePerThousand','Số tiền trung bình trên 1.000 lượt',input.revenuePerThousand,'35,000')+moneyField('fixedCosts','Tổng chi phí hàng tháng',input.fixedCosts,'15,000,000')+targetField(input.targetProfit);if(t==='lead')return'<div class="modeNote"><b>Tạo khách hàng tiềm năng</b> - không coi mọi lead là doanh thu; chỉ phần đủ điều kiện mới được tính.</div>'+numberField('leads','Số lead tạo được mỗi tháng',input.leads,'1000','lead/tháng')+numberField('qualifiedRate','Tỷ lệ lead đủ điều kiện để được trả tiền',input.qualifiedRate,'20','%')+moneyField('revenuePerQualifiedLead','Mức thu trên một lead đủ điều kiện',input.revenuePerQualifiedLead,'150,000')+moneyField('fixedCosts','Tổng chi phí hàng tháng',input.fixedCosts,'20,000,000')+targetField(input.targetProfit);return'<div class="modeNote"><b>MMO - Tự nhập</b> - dùng một đơn vị tạo tiền do bạn đặt.</div>'+`<div class="field"><label>Bạn muốn gọi một đơn vị tạo tiền là gì?</label><input data-plan-key="unitLabel" value="${escAttr(input.unitLabel||'')}" placeholder="Ví dụ: lượt mua, lượt tải, phiên"></div>`+moneyField('price','Số tiền thu được trên một đơn vị',input.price,'100,000')+moneyField('directCost','Chi phí trực tiếp trên một đơn vị',input.directCost,'20,000')+numberField('volume','Số đơn vị dự kiến mỗi tháng',input.volume,'500','/tháng')+moneyField('fixedCosts','Tổng chi phí hàng tháng',input.fixedCosts,'15,000,000')+targetField(input.targetProfit)}
function recurringPlanFields(s,input){const b=s.config?.billing||'month';let html='<div class="modeNote"><b>Thu phí định kỳ</b> - chu kỳ đã chọn: <b>'+esc(labelBilling(s.config))+'</b>. Gói dài hơn một tháng sẽ được backend quy đổi về tháng.</div>';if(b==='both'){html+=numberField('monthlySubscribers','Người đang trả gói tháng',input.monthlySubscribers,'140','người')+moneyField('monthlyPrice','Giá gói tháng',input.monthlyPrice,'199,000')+numberField('yearlySubscribers','Người đang trả gói năm',input.yearlySubscribers,'60','người')+moneyField('yearlyPrice','Giá gói năm',input.yearlyPrice,'1,990,000')}else{html+=numberField('activeSubscribers','Số người đang trả phí',input.activeSubscribers,'200','người')+moneyField('pricePerCycle',b==='year'?'Mỗi người trả bao nhiêu mỗi năm?':b==='custom'?'Mỗi người trả bao nhiêu mỗi chu kỳ?':'Mỗi người trả bao nhiêu mỗi tháng?',input.pricePerCycle,b==='year'?'1,990,000':'199,000')}html+=numberField('newSubscribers','Mỗi tháng có thêm khoảng bao nhiêu người trả phí?',input.newSubscribers,'25','người/tháng')+numberField('lostSubscribers','Mỗi tháng khoảng bao nhiêu người ngừng trả?',input.lostSubscribers,'12','người/tháng')+moneyField('variablePerSubscriber','Chi phí tăng thêm cho mỗi người đang dùng / tháng',input.variablePerSubscriber,'20,000','Ví dụ: server, API, support hoặc license phát sinh theo số người dùng.')+moneyField('fixedCosts','Chi phí cố định mỗi tháng',input.fixedCosts,'20,000,000')+targetField(input.targetProfit);return html}
function genericPlanFields(s,input){const u=s.config?.unit||'đơn vị';return'<div class="modeNote"><b>Khác / Tự nhập</b> - MBA dùng đơn vị bạn đã khai báo: <b>'+esc(u)+'</b>.</div>'+moneyField('price','Số tiền thu được cho một '+u,input.price,'500,000')+moneyField('directCost','Chi phí trực tiếp cho một '+u,input.directCost,'100,000')+numberField('volume','Số '+u+' dự kiến mỗi tháng',input.volume,'50',u+'/tháng')+moneyField('fixedCosts','Tổng chi phí hàng tháng',input.fixedCosts,'10,000,000')+targetField(input.targetProfit)}
function planChoiceBlock(label,key,items,selected){return`<div class="field"><label>${label}</label><div class="choiceGrid" data-plan-choice="${key}">${items.map(([v,t,sub])=>`<button type="button" class="choice ${selected===v?'selected':''}" data-value="${v}">${t}${sub?`<small>${sub}</small>`:''}</button>`).join('')}</div></div>`}
function bindPlanUI(){bindMoneyInputs();$$('[data-plan-choice] .choice').forEach(b=>b.onclick=()=>{const g=b.closest('[data-plan-choice]');g.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');refreshPlanVisibility()});refreshPlanVisibility()}
function refreshPlanVisibility(){const mode=$('[data-plan-choice="capacity.mode"] .choice.selected')?.dataset.value||'none';$$('[data-cap-section]').forEach(x=>x.classList.toggle('on',x.dataset.capSection===mode));const rp=$('[data-plan-choice="capacity.realisticPreset"] .choice.selected')?.dataset.value;const box=$('[data-realistic-custom]');if(box)box.classList.toggle('on',rp==='custom')}
function bindMoneyInputs(){$$('.money').forEach(el=>{if(el.dataset.bound)return;el.dataset.bound='1';el.addEventListener('input',e=>{const d=e.target.value.replace(/\D/g,'');e.target.value=d?Number(d).toLocaleString('en-US'):''})})}
function readPlanInput(){const out={};$$('[data-plan-key]').forEach(el=>setNested(out,el.dataset.planKey,el.value));$$('[data-plan-choice]').forEach(g=>setNested(out,g.dataset.planChoice,g.querySelector('.choice.selected')?.dataset.value||''));const preset=getNested(out,'capacity.realisticPreset');if(preset&&preset!=='custom')setNested(out,'capacity.realisticPct',preset);return out}
function setNested(obj,path,value){const parts=path.split('.');let x=obj;parts.forEach((p,i)=>{if(i===parts.length-1)x[p]=value;else{x[p]=x[p]||{};x=x[p]}})}
function getNested(obj,path){return path.split('.').reduce((x,k)=>x?.[k],obj)}
async function calculatePlan(){const s=currentStream();if(!s)return;const input=readPlanInput();const btn=$('#calculateBtn');btn.disabled=true;btn.textContent='Đang tính...';try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:s.model,config:s.config,input})});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();if(data.status!=='ok'){toast(data.message||'Chưa thể tính với dữ liệu này.');return}s.planning={mode:'quick',input,result:data,updatedAt:now()};const p=currentProfile();p.updatedAt=now();persist();renderPlanResult(s,data);go('planResult')}catch(e){toast('Không kết nối được với bộ máy tính MBA. Thử lại sau ít phút.')}finally{btn.disabled=false;btn.textContent='Xem kết quả'}}
function renderPlanResult(s,data){$('#resultEyebrow').textContent=MODEL_META[s.model].label;$('#resultTitle').textContent=s.name;$('#heroLabel').textContent=data.hero.label;$('#heroValue').textContent=formatMetric(data.hero);$('#metricGrid').innerHTML=(data.metrics||[]).map(m=>`<div class="metric"><label>${esc(m.label)}</label><div class="value">${esc(formatMetric(m))}</div>${m.sub?`<div class="sub">${esc(m.sub)}</div>`:''}</div>`).join('');$('#insightText').textContent=data.insight||'';const assumptions=data.assumptions||[];$('#assumptions').innerHTML=assumptions.length?`<b>Giả định đang dùng</b><ul>${assumptions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'';$('#assumptions').classList.toggle('hidden',!assumptions.length)}
function editCurrentPlan(){const s=currentStream();if(s)openPlanning(s.id)}
function backToBuilderFromResult(){renderBuilder();go('builder')}
function formatMetric(m){if(m?.format==='money')return formatMoney(Number(m.value)||0);const val=new Intl.NumberFormat('vi-VN',{maximumFractionDigits:1}).format(Number(m?.value)||0);return val+(m?.unit?' '+m.unit:'')}
function formatMoney(v){const sign=v<0?'- ':'';const a=Math.abs(v);if(a>=1000000){const m=a/1000000;return sign+new Intl.NumberFormat('vi-VN',{maximumFractionDigits:1}).format(m)+' triệu'}return sign+new Intl.NumberFormat('vi-VN',{maximumFractionDigits:0}).format(a)+'đ'}
function moneyInputValue(v){if(v==null||v==='')return'';const n=Number(String(v).replace(/,/g,''));return Number.isFinite(n)&&n?Math.round(n).toLocaleString('en-US'):''}
function serviceUnit(c){return c.basis==='visit'?'lượt':c.basis==='hour'?'giờ':c.basis==='project'?'dự án':c.basis==='client'?'khách hàng':c.basisCustom||'đơn vị'}
function val(id){return $('#'+id)?.value.trim()||''}
function formatDate(iso){try{return new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(iso))}catch(e){return''}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function escAttr(s){return esc(s)}
syncHeader();
