const BUSINESS_API_URL='https://linkedin-tools-api-test.vercel.app/api/mba-business';
const SHARED_DEFAULTS=[
  ['rent','Mặt bằng dùng chung'],
  ['people','Nhân sự dùng chung'],
  ['utilities','Điện, nước, Internet dùng chung'],
  ['accounting','Kế toán / hành chính'],
  ['software','Phần mềm / công cụ dùng chung'],
  ['brand','Marketing thương hiệu chung'],
  ['management','Chi phí quản lý chung']
];
let allocationMethod='none',customAllocationMode='percent';

const _m2RenderBuilder=renderBuilder;
renderBuilder=function(){_m2RenderBuilder();const p=currentProfile();const footer=$('#builder .builderFooter');if(footer){let old=$('#m3Status');if(old)old.remove();const planned=p?.streams.filter(s=>s.planning?.result?.status==='ok').length||0;if(p?.businessPlan?.result?.status==='ok'){const d=document.createElement('div');d.id='m3Status';d.className='callout';d.style.margin='0 0 14px';d.innerHTML='<b>Đã có kết quả toàn hồ sơ</b> · Lợi nhuận ước tính '+esc(formatMoney(p.businessPlan.result.summary.businessProfit))+'. Bạn có thể mở lại để cập nhật chi phí dùng chung hoặc cách phân bổ.';footer.prepend(d)}const btn=footer.querySelector('.actions .btn:not(.secondary)');if(btn)btn.textContent=planned===p?.streams.length&&planned>0?'Tổng hợp toàn hồ sơ':'Kiểm tra kế hoạch các nguồn'}};
const _m2CalculatePlan=calculatePlan;
calculatePlan=async function(){const p=currentProfile();if(p){p.businessPlan=null;persist()}return _m2CalculatePlan()};
const _m2SaveStream=saveStream;
saveStream=function(){const p=currentProfile();if(p){p.businessPlan=null;persist()}return _m2SaveStream()};
const _m2DeleteSource=deleteSource;
deleteSource=function(id){const p=currentProfile();if(p){p.businessPlan=null;persist()}return _m2DeleteSource(id)};
finishStructure=function(){openM3()};

function openM3(){
  const p=currentProfile();if(!p||!p.streams.length){toast('Cần ít nhất một nguồn thu.');return}
  const missing=p.streams.filter(s=>s.planning?.result?.status!=='ok');
  if(missing.length){renderBuilder();go('builder');toast('Còn '+missing.length+' nguồn thu chưa có Kế hoạch nhanh. Hoàn thiện các nguồn này trước khi tổng hợp.');return}
  renderSharedCosts();go('sharedCosts');
}
function sharedPlan(){const p=currentProfile();return p?.businessPlan||{sharedCosts:[],allocation:{method:'none',customMode:'percent',custom:{}},result:null}}
function renderSharedCosts(){
  const p=currentProfile(),bp=sharedPlan(),map={};(bp.sharedCosts||[]).forEach(x=>map[x.id]=x);
  $('#sharedProfileName').textContent=p.name;
  $('#sharedStandardRows').innerHTML=SHARED_DEFAULTS.map(([id,label])=>`<div class="sharedGrid"><label>${label}</label><div class="amount"><input class="money" data-shared-id="${id}" value="${moneyInputValue(map[id]?.amount||'')}" inputmode="numeric" placeholder="0"><span>đ</span></div></div>`).join('');
  const custom=(bp.sharedCosts||[]).filter(x=>x.custom);$('#otherSharedRows').innerHTML='';if(custom.length)custom.forEach(x=>addOtherSharedRow(x.name,x.amount));else addOtherSharedRow('',0);
  allocationMethod=bp.allocation?.method||'none';customAllocationMode=bp.allocation?.customMode||'percent';renderAllocationOptions(bp.allocation?.custom||{});bindMoneyInputs();updateSharedTotal();
  $$('[data-shared-id]').forEach(x=>x.addEventListener('input',updateSharedTotal));
}
function addOtherSharedRow(name='',amount=0){const host=$('#otherSharedRows'),row=document.createElement('div');row.className='otherRow';row.innerHTML=`<input data-other-name placeholder="Tên khoản khác" value="${escAttr(name)}"><div class="amount"><input class="money" data-other-amount inputmode="numeric" value="${moneyInputValue(amount)}" placeholder="0"><span>đ</span></div><button type="button" class="removeOther" aria-label="Xóa khoản">×</button>`;host.appendChild(row);row.querySelector('.removeOther').onclick=()=>{row.remove();updateSharedTotal()};row.querySelector('[data-other-amount]').addEventListener('input',updateSharedTotal);bindMoneyInputs()}
function readSharedCosts(){const items=[];SHARED_DEFAULTS.forEach(([id,label])=>{const el=$(`[data-shared-id="${id}"]`),amount=parseMoney(el?.value);if(amount>0)items.push({id,name:label,amount,custom:false})});$$('#otherSharedRows .otherRow').forEach((row,i)=>{const name=row.querySelector('[data-other-name]')?.value.trim(),amount=parseMoney(row.querySelector('[data-other-amount]')?.value);if(name&&amount>0)items.push({id:'other_'+i+'_'+name.slice(0,12),name,amount,custom:true})});return items}
function updateSharedTotal(){const total=readSharedCosts().reduce((a,x)=>a+x.amount,0);$('#sharedTotal').textContent=formatMoney(total);if(allocationMethod==='custom')renderCustomAllocationInputs(readExistingCustomAllocation())}
function renderAllocationOptions(existing={}){const choices=[['none','Không phân bổ','Chỉ trừ một lần ở cấp toàn hồ sơ. Phù hợp nếu bạn chỉ cần biết kết quả chung.'],['revenue','Theo tỷ trọng doanh thu','Nguồn tạo nhiều doanh thu gánh phần chi phí chung lớn hơn.'],['equal','Chia đều','Mỗi nguồn thu gánh một phần bằng nhau.'],['contribution','Theo phần còn lại trước chi phí dùng chung','Nguồn đang để lại nhiều tiền hơn gánh phần lớn hơn.'],['custom','Tự phân bổ','Bạn tự nhập tỷ lệ hoặc số tiền cho từng nguồn.']];$('#allocationChoices').innerHTML=choices.map(([v,t,sub])=>`<button type="button" class="choice ${allocationMethod===v?'selected':''}" data-allocation="${v}">${t}<small>${sub}</small></button>`).join('');$$('[data-allocation]').forEach(b=>b.onclick=()=>{allocationMethod=b.dataset.allocation;$$('[data-allocation]').forEach(x=>x.classList.toggle('selected',x===b));$('#customAllocationBox').classList.toggle('on',allocationMethod==='custom');if(allocationMethod==='custom')renderCustomAllocationInputs(existing)});$('#customAllocationBox').classList.toggle('on',allocationMethod==='custom');renderAllocationMode(existing);if(allocationMethod==='custom')renderCustomAllocationInputs(existing)}
function renderAllocationMode(existing={}){$('#allocationModeChoices').innerHTML=[['percent','Theo %'],['amount','Theo số tiền']].map(([v,t])=>`<button type="button" class="choice ${customAllocationMode===v?'selected':''}" data-allocation-mode="${v}">${t}</button>`).join('');$$('[data-allocation-mode]').forEach(b=>b.onclick=()=>{customAllocationMode=b.dataset.allocationMode;$$('[data-allocation-mode]').forEach(x=>x.classList.toggle('selected',x===b));renderCustomAllocationInputs(existing)})}
function readExistingCustomAllocation(){const out={};$$('[data-custom-allocation]').forEach(x=>out[x.dataset.customAllocation]=x.value);return out}
function renderCustomAllocationInputs(existing={}){const p=currentProfile(),total=readSharedCosts().reduce((a,x)=>a+x.amount,0),suffix=customAllocationMode==='percent'?'%':'đ';$('#customAllocationRows').innerHTML=p.streams.map(s=>`<div class="allocationRow"><label>${esc(s.name)}</label><div class="amount"><input ${customAllocationMode==='amount'?'class="money"':''} data-custom-allocation="${s.id}" inputmode="decimal" value="${customAllocationValue(existing[s.id],customAllocationMode)}" placeholder="0"><span>${suffix}</span></div></div>`).join('');bindMoneyInputs();$$('[data-custom-allocation]').forEach(x=>x.addEventListener('input',updateAllocationSummary));$('#customAllocationHelp').textContent=customAllocationMode==='percent'?'Tổng tỷ lệ phải bằng 100%.':'Tổng số tiền phải bằng đúng '+formatMoney(total)+'.';updateAllocationSummary()}
function customAllocationValue(v,mode){if(v==null||v==='')return'';if(mode==='amount')return moneyInputValue(v);return String(v).replace(/,/g,'')}
function updateAllocationSummary(){const vals=$$('[data-custom-allocation]').map(x=>customAllocationMode==='amount'?parseMoney(x.value):(parseFloat(x.value)||0)),sum=vals.reduce((a,b)=>a+b,0),total=readSharedCosts().reduce((a,x)=>a+x.amount,0);$('#allocationSummary').textContent=customAllocationMode==='percent'?'Đã phân bổ '+new Intl.NumberFormat('vi-VN',{maximumFractionDigits:1}).format(sum)+'% / 100%':'Đã phân bổ '+formatMoney(sum)+' / '+formatMoney(total)}
function collectAllocation(){let method=allocationMethod,custom={};if(method==='custom'){method=customAllocationMode==='percent'?'custom_percent':'custom_amount';$$('[data-custom-allocation]').forEach(x=>custom[x.dataset.customAllocation]=customAllocationMode==='amount'?parseMoney(x.value):(parseFloat(x.value)||0))}return{method,customMode:customAllocationMode,custom}}
function streamsForBusinessApi(){return currentProfile().streams.map(s=>{const x=s.planning.result.summary||{};return{id:s.id,name:s.name,model:s.model,monthlyRevenue:x.monthlyRevenue||0,monthlyContribution:x.monthlyContribution||0,monthlyProfit:x.monthlyProfit||0,fixedCosts:x.fixedCosts||0}})}
async function calculateBusiness(){const p=currentProfile(),sharedCosts=readSharedCosts(),allocation=collectAllocation(),btn=$('#businessCalculateBtn');btn.disabled=true;btn.textContent='Đang tổng hợp...';try{const r=await fetch(BUSINESS_API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({streams:streamsForBusinessApi(),sharedCosts,allocation})});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();if(data.status!=='ok'){toast(data.message||'Chưa thể tổng hợp với dữ liệu này.');return}p.sharedCosts=sharedCosts;p.businessPlan={sharedCosts,allocation,result:data,updatedAt:now()};p.updatedAt=now();persist();renderBusinessResult(data);go('businessResult')}catch(e){toast('Không kết nối được với bộ máy tổng hợp MBA. Thử lại sau ít phút.')}finally{btn.disabled=false;btn.textContent='Xem kết quả toàn hồ sơ'}}
function renderBusinessResult(data){const p=currentProfile();$('#businessResultName').textContent=p.name;$('#businessHeroLabel').textContent=data.hero.label;$('#businessHeroValue').textContent=formatMetric(data.hero);$('#businessMetrics').innerHTML=(data.metrics||[]).map(m=>`<div class="metric"><label>${esc(m.label)}</label><div class="value">${esc(formatMetric(m))}</div></div>`).join('');$('#businessInsight').textContent=data.insight||'';$('#allocationLabel').textContent='Cách xử lý chi phí dùng chung: '+allocationLabel(data.allocation?.method||'none');renderStreamTable(data);renderDistributions(data);const assumptions=data.assumptions||[];$('#businessAssumptions').innerHTML=assumptions.length?`<b>Giả định đang dùng</b><ul>${assumptions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'';$('#businessAssumptions').classList.toggle('hidden',!assumptions.length)}
function allocationLabel(method){return method==='none'?'Không phân bổ':method==='revenue'?'Theo tỷ trọng doanh thu':method==='equal'?'Chia đều':method==='contribution'?'Theo phần còn lại trước chi phí dùng chung':method==='custom_percent'?'Tự phân bổ theo %':method==='custom_amount'?'Tự phân bổ theo số tiền':'Tự chọn'}
function renderStreamTable(data){const allocated=data.allocation?.method!=='none';$('#streamResultTable').innerHTML=`<div class="tr th"><div>Nguồn thu</div><div class="num">Doanh thu</div><div class="num">Trước CP chung</div><div class="num">CP chung phân bổ</div><div class="num">Sau phân bổ</div></div>`+(data.streams||[]).map(s=>`<div class="tr"><div class="name"><strong>${esc(s.name)}</strong><span>${esc(MODEL_META[s.model]?.label||s.model)}</span></div><div class="num">${esc(formatMoney(s.monthlyRevenue))}</div><div class="num">${esc(formatMoney(s.monthlyProfit))}</div><div class="num">${allocated?esc(formatMoney(s.allocatedSharedCost||0)):'-'}</div><div class="num">${allocated?esc(formatMoney(s.profitAfterAllocation||0)):'-'}</div></div>`).join('')}
function renderDistributions(data){const rows=data.streams||[],totalRevenue=rows.reduce((a,s)=>a+s.monthlyRevenue,0),positiveProfit=rows.reduce((a,s)=>a+Math.max(0,s.monthlyProfit),0);$('#revenueDistribution').innerHTML=distributionHtml('100 đồng doanh thu đến từ đâu?',rows.map(s=>({name:s.name,pct:totalRevenue?s.monthlyRevenue/totalRevenue*100:0})));$('#profitDistribution').innerHTML=positiveProfit>0?distributionHtml('100 đồng phần còn lại trước chi phí dùng chung đến từ đâu?',rows.filter(s=>s.monthlyProfit>0).map(s=>({name:s.name,pct:s.monthlyProfit/positiveProfit*100}))):'<div class="distributionCard"><h3>Phần còn lại trước chi phí dùng chung</h3><p class="hint">Chưa có nguồn nào để lại số dương theo kế hoạch hiện tại.</p></div>'}
function distributionHtml(title,rows){return`<div class="distributionCard"><h3>${title}</h3>${rows.map(x=>`<div class="barRow"><div>${esc(x.name)}</div><div class="barTrack"><div class="barFill" style="width:${Math.max(0,Math.min(100,x.pct))}%"></div></div><div class="barPct">${new Intl.NumberFormat('vi-VN',{maximumFractionDigits:1}).format(x.pct)}đ</div></div>`).join('')}</div>`}
function editBusinessPlan(){renderSharedCosts();go('sharedCosts')}
function parseMoney(v){return Number(String(v||'').replace(/[^0-9.-]/g,''))||0}
